source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Optik_Example' do
  pod 'Optik', :path => '../'
  pod 'AlamofireImage', '3.0.0'
end

target 'Optik_Tests' do
  pod 'Optik', :path => '../'
end
