source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Optik_Example' do
    platform :ios, '10.1'

    pod 'Optik', :path => '../'
    pod 'AlamofireImage', '3.5.2'
end

target 'Optik_Tests' do
    platform :ios, '10.1'

    pod 'Optik', :path => '../'
end
