source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Optik_Example' do
    platform :ios, '9.0'

    pod 'Optik', :path => '../'
    pod 'AlamofireImage', '~> 3.4'
end

target 'Optik_Tests' do
    platform :ios, '9.0'

    pod 'Optik', :path => '../'
end
